### ISSUE TITLE
don't run

### ISSUE THREAD

**Issue by chuckxD** [SaraVieira/make-frontend-shit-again#28]
```
$ npm run dev

> make-frontend-shit-again@1.0.0 dev /Users/alex.merrifield/make-frontend-shit-again
> nuxt

/Users/alex.merrifield/make-frontend-shit-again/node_modules/nuxt/lib/core/module.js:14
  async ready() {
        ^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alex.merrifield/make-frontend-shit-again/node_modules/nuxt/lib/core/index.js:2:16)
    at Module._compile (module.js:570:32)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/alex.merrifield/.nvm/versions/node/v6.9.4/bin/node" "/Users/alex.merrifield/.nvm/versions/node/v6.9.4/bin/npm" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! make-frontend-shit-again@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the make-frontend-shit-again@1.0.0 dev script 'nuxt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the make-frontend-shit-again package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs make-frontend-shit-again
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls make-frontend-shit-again
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alex.merrifield/make-frontend-shit-again/npm-debug.log
```

**Comment by SaraVieira** [comment]
Hey!

Nuxt expects at least version 8 of node :(
